Vinoteca/Vinoteca.Web/ViewModels/Producto/ProductoEditVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Vinoteca.Web.ViewModels.Producto
{
    public class ProductoEditVm
    {
        public int ProductoId { get; set; }
        [DisplayName("Producto")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(100, ErrorMessage = "El campo {0} debe contener entre {2} y {1} caracteres", MinimumLength = 3)]
        public string Descripcion { get; set; }
        [DisplayName("Variedad")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar una categoría")]

        public int VariedadId { get; set; }
        [DisplayName("Tipo de Producto")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar un tipo de producto")]
        public int TipoProductoId { get; set; }
        [DisplayName("Precio")]
        [Required(ErrorMessage = "El precio es requerido")]
        [Range(0.10, 10000, ErrorMessage = "Favor de ingresar un {0} entre {1} y{2}")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal PrecioVenta { get; set; }
        [DisplayName("Ficha técnica")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(1500, ErrorMessage = "El campo {0} debe contener entre {2} y {1} caracteres", MinimumLength = 3)]
        public string FichaTecnica { get; set; }
        [DisplayName("Bodega")]
        [Range(1, int.MaxValue, ErrorMessage = "Debe seleccionar una bodega")]
        public int BodegaId { get; set; }
        public bool Suspendido { get; set; } = false;

        public int UnidadesEnPedido { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Stock mal ingresado")]
        public int Stock { get; set; }
        
        [DataType(DataType.ImageUrl)]
        public string Imagen { get; set; }
        [DisplayName("Imagen")]
        public HttpPostedFileBase imagenFile { get; set; }
        public byte[] RowVersion { get; set; }
        public List<SelectListItem> Bodegas { get; set; }
        public List<SelectListItem> Variedades { get; set; }
        public List<SelectListItem> TiposProductos { get; set; }
    }
}

Vinoteca/Vinoteca.Web/ViewModels/Producto/ProductoListVm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Vinoteca.Web.ViewModels.Producto
{
    public class ProductoListVm
    {
        public int ProductoId { get; set; }
        [DisplayName("Producto")]
        public string Descripcion { get; set; }
        public string Variedad { get; set; }

        [DisplayName("Precio")]
        public decimal PrecioVenta { get; set; }
        public string Bodega { get; set; }
        public int Stock { get; set; }
        public bool Suspendido { get; set; }
        [DisplayName("Imágen")]
        public string Imagen { get; set; }
    }
}

Vinoteca/Vinoteca.Web/Controllers/ProductosController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.IO;
using System.Web.Mvc;
using System.Web.UI;
using Vinoteca.Entidades.Entidades;
using Vinoteca.Servicios.Interfaces;
using Vinoteca.Utilidades;
using Vinoteca.Web.App_Start;
using Vinoteca.Web.ViewModels.Producto;
using Vinoteca.Web.ViewModels.Variedad;

namespace Vinoteca.Web.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Productos
        private readonly IServiciosProductos _servicios;
        private readonly IServiciosBodegas _serviciosBodegas;
        private readonly IServiciosVariedades _serviciosVariedades;
        private readonly IServiciosTipoProductos _serviciosTipoProductos;
        private readonly IMapper _mapper;
        public ProductosController(IServiciosProductos servicios,
            IServiciosBodegas serviciosBodegas,
            IServiciosVariedades serviciosVariedades,
            IServiciosTipoProductos serviciosTipoProductos)
        {
            _servicios = servicios;
            _serviciosBodegas = serviciosBodegas;
            _serviciosVariedades = serviciosVariedades;
            _serviciosTipoProductos = serviciosTipoProductos;
            _mapper = AutoMapperConfig.Mapper;
        }
        // GET: Productos
        public ActionResult Index(int? page, int? pageSize)
        {
            var lista = _servicios.GetProductos();
            var listaVm = _mapper.Map<List<ProductoListVm>>(lista);
            page = page ?? 1;
            pageSize = pageSize ?? 10;
            ViewBag.PageSize = pageSize;

            return View(listaVm.ToPagedList(page.Value, pageSize.Value));
        }
        [Authorize]
        public ActionResult Create()
        {
            var productoVm = new ProductoEditVm
            {
                Bodegas = _serviciosBodegas.GetBodegasDropDownList(),
                Variedades = _serviciosVariedades.GetVariedadesDropDownList(),
                TiposProductos = _serviciosTipoProductos.GetTipoProductosDropDownList()
            };
            return View(productoVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductoEditVm productoVm)
        {
            if (!ModelState.IsValid)
            {
                productoVm.Bodegas = _serviciosBodegas.GetBodegasDropDownList();
                productoVm.Variedades = _serviciosVariedades.GetVariedadesDropDownList();
                productoVm.TiposProductos = _serviciosTipoProductos.GetTipoProductosDropDownList();
                return View(productoVm);
            }
            try
            {
                var producto = _mapper.Map<Producto>(productoVm);
                if (!_servicios.Existe(producto))
                {
                    if (productoVm.imagenFile != null)
                    {
                        string extension = Path.GetExtension(productoVm.imagenFile.FileName);
                        string filename = Guid.NewGuid().ToString();

                        var file = $"{filename}{extension}";
                        var response = FileHelper.UploadPhoto(productoVm.imagenFile, WC.Vino1, file);
                        producto.Imagen = file;
                    }

                    _servicios.Guardar(producto);
                    TempData["Msg"] = "Registro agregado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Producto existente!!!");
                    productoVm.Bodegas = _serviciosBodegas.GetBodegasDropDownList();
                    productoVm.Variedades = _serviciosVariedades.GetVariedadesDropDownList();
                    productoVm.TiposProductos = _serviciosTipoProductos.GetTipoProductosDropDownList();

                    return View(productoVm);
                }
            }
            catch (System.Exception)
            {

                ModelState.AddModelError(string.Empty, "Error al intentar agregar un Producto");
                productoVm.Bodegas = _serviciosBodegas.GetBodegasDropDownList();
                productoVm.Variedades = _serviciosVariedades.GetVariedadesDropDownList();
                productoVm.TiposProductos = _serviciosTipoProductos.GetTipoProductosDropDownList();

                return View(productoVm);
            }
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var producto = _servicios.GetProductoPorId(id.Value);
            if (producto == null)
            {
                return HttpNotFound("Código de producto inexistente");
            }
            var productoVm = _mapper.Map<ProductoEditVm>(producto);
            productoVm.Bodegas = _serviciosBodegas.GetBodegasDropDownList();
            productoVm.Variedades = _serviciosVariedades.GetVariedadesDropDownList();
            productoVm.TiposProductos = _serviciosTipoProductos.GetTipoProductosDropDownList();
            return View (productoVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit (ProductoEditVm productoVm)
        {
            if (!ModelState.IsValid)
            {
                productoVm.Bodegas = _serviciosBodegas.GetBodegasDropDownList();
                productoVm.Variedades = _serviciosVariedades.GetVariedadesDropDownList();
                productoVm.TiposProductos = _serviciosTipoProductos.GetTipoProductosDropDownList();
                return View(productoVm);
            }
            try
            {
                var producto = _mapper.Map<Producto>(productoVm);
                if (!_servicios.Existe(producto))
                {
                    _servicios.Guardar(producto);
                    TempData["Msg"] = "Registro editado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "¡Producto existente!");
                    productoVm.Bodegas = _serviciosBodegas.GetBodegasDropDownList();
                    productoVm.Variedades = _serviciosVariedades.GetVariedadesDropDownList();
                    productoVm.TiposProductos = _serviciosTipoProductos.GetTipoProductosDropDownList();
                    return View(productoVm);

                }
            }
            catch (System.Exception)
            {
                ModelState.AddModelError(string.Empty, "¡Producto existente!");
                productoVm.Bodegas = _serviciosBodegas.GetBodegasDropDownList();
                productoVm.Variedades = _serviciosVariedades.GetVariedadesDropDownList();
                productoVm.TiposProductos = _serviciosTipoProductos.GetTipoProductosDropDownList();
                return View(productoVm);
            }
        }

        [Authorize]
        public ActionResult Delete (int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var producto = _servicios.GetProductoPorId(id.Value);
            if (producto == null)
            {
                return HttpNotFound("Código de producto inexistente");
            }
            var productoVm = _mapper.Map<ProductoListVm>(producto);
            return View (productoVm);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            var producto = _servicios.GetProductoPorId(id);
            var productoVm = _mapper.Map<ProductoListVm>(producto);
            try
            {
                if (!_servicios.EstaRelacionado(producto))
                {
                    _servicios.Borrar(id);
                    TempData["Msg"] = "Producto borrado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Registro relacionado... Baja denegada");
                    return View(productoVm);
                }
            }
            catch (System.Exception)
            {
                ModelState.AddModelError(string.Empty, "Error al intengar borrar un proveedor");
                return View(productoVm);
            }
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var producto = _servicios.GetProductoPorId(id.Value);
            if (producto == null)
            {
                return HttpNotFound("Cód. producto inexistente!!!");
            }
            var productoVm = _mapper.Map<ProductoListVm>(producto);
            return View(productoVm);
        }
    }
}

Vinoteca/Vinoteca.Web/Views/Productos/Create.cshtml
@model Vinoteca.Web.ViewModels.Producto.ProductoEditVm

@{
    ViewBag.Title = "Create";
}

<h2>Nuevo Producto</h2>

@using (Html.BeginForm("Create", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
  
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("_MostrarProducto", Model)
  
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default btn-primary" />
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

Vinoteca/Vinoteca.Web/Views/Productos/Delete.cshtml
@model Vinoteca.Web.ViewModels.Producto.ProductoListVm

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>¿Está seguro/a que desea eliminar el siguiente producto?</h3>
<div>
    <hr />
    <div class="row">
        <div class="col-8">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Descripcion)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Variedad)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Variedad)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PrecioVenta)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PrecioVenta)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UnidadesDisponibles)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UnidadesDisponibles)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Bodega)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Bodega)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Stock)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Stock)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Suspendido)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Suspendido)
                </dd>
            </dl>
        </div>
        <div class="col-4">
            <div class="form-group">
                @Html.DisplayNameFor(model => model.Imagen)
                @if (Model.Imagen != null)
                {
                    <img src="@Url.Content(Vinoteca.Utilidades.WC.ProductosImagenesFolder + Model.Imagen)" style="width:100px; height:100px" />
                }
                else
                {
                    <img src = "@Url.Content(Vinoteca.Utilidades.WC.SinImagenDisponible)" style = "width:100px; height:100px" />
                }
            </div>
        </div>
    </div>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
        </div>
    }
</div>

Vinoteca/Vinoteca.Web/Views/Productos/Details.cshtml
@model Vinoteca.Web.ViewModels.Producto.ProductoListVm
@{
    ViewBag.Title = "Details";
}

<h2>Detalle del Producto</h2>
<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            @if (Model.Imagen == null)
            {
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="@Url.Content(Vinoteca.Utilidades.WC.SinImagenDisponible)" style="width:500px; height:500px" /></div>

            }
            else
            {
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="@Url.Content(Vinoteca.Utilidades.WC.ProductosImagenesFolder+Model.Imagen)" style="width:500px; height:500px" /></div>

            }
        <div class="col-md-6">
            <div class="small mb-1">@Model.Bodega</div>
            <div class="small mb-1">@Model.Variedad</div>
            <h1 class="display-5 fw-bolder">@Model.Descripcion</h1>
            <div class="fs-5 mb-5">
                <span class="text-decoration-line-through">@(Model.PrecioVenta+500)</span>
                <span>@Model.PrecioVenta</span>
            </div>
            <p class="lead">Stock: <strong>@Model.Stock</strong> </p>
            @using (Html.BeginForm("AddToCart", "Carrito", FormMethod.Post))
            {
                <div class="d-flex">
                    @Html.Hidden("productoId", Model.ProductoId)
                    @Html.Hidden("returnUrl", "/Productos/")
                    <input class="form-control text-center me-3" name="cantidad" id="inputQuantity" type="number" value="1" style="max-width: 3rem" />
                    <button class="btn btn-outline-dark flex-shrink-0 me-3" type="submit">
                        <i class="fa fa-shopping-cart me-1"></i>
                        Comprar
                    </button>
                    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
                </div>
            }
        </div>
        </div>
    </div>
</section>

Vinoteca/Vinoteca.Web/Views/Productos/Edit.cshtml
@model Vinoteca.Web.ViewModels.Producto.ProductoEditVm

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Producto</h2>

@using (Html.BeginForm("Edit", "Productos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ProductoId)
        @Html.HiddenFor(model => model.RowVersion)
        @Html.HiddenFor(model => model.imagenFile)

        @Html.Partial("_MostrarProducto", Model)


        <div class="form-group mt-3">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-warning" />
                @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

Vinoteca/Vinoteca.Web/Views/Productos/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<Vinoteca.Web.ViewModels.Producto.ProductoListVm>

@{
    ViewBag.Title = "Index";
}
@*<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>*@

<div class="d-flex justify-content-between w-95">
    <h2>Lista de Vinos</h2>
    <p>
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-primary" })
        }

    </p>
</div>


<table class="border-0 table table-bordered table-hover table-dark w-100">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Variedad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().PrecioVenta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Bodega)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Stock)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Suspendido)
        </th>
        <th style="width:150px">
            @Html.DisplayNameFor(model => model.FirstOrDefault().Imagen)
        </th>
        @if (User.IsInRole("Admin") || User.IsInRole("Usuario"))
        {
            <th style="width:220px">Acciones</th>
        }

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Variedad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrecioVenta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bodega)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Suspendido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Imagen)
            </td>
            @if (User.IsInRole("Admin") || User.IsInRole("Usuario"))
            {
                <td>
                    @if (User.IsInRole("Admin"))
                    {
                        @Html.ActionLink("Editar", "Edit", new { id = item.ProductoId }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Detalles", "Details", new { id = item.ProductoId }, new { @class = "btn btn-info" })
                        @Html.ActionLink("Borrar", "Delete", new { id = item.ProductoId }, new { @class = "btn btn-danger" })
                    }
                    @if (User.IsInRole("Usuario"))
                    {
                        using (Html.BeginForm("AddToCart", "Carrito", FormMethod.Post))
                        {
                            @Html.ActionLink("Detalles", "Details", new { id = item.ProductoId }, new { @class = "btn btn-info" })

                            @Html.Hidden("productoId", item.ProductoId)
                            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                            <button type="submit" class="btn btn-outline-danger">
                                Comprar
                            </button>
                        }
                    }

                </td>
            }
        </tr>
    }

</table>
<div class="pagination-container">
    <div class="pagination-buttons">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                @if (Model.HasPreviousPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber - 1, pageSize = ViewBag.PageSize })">Anterior</a>
                    </li>
                }
                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                        <a class="page-link" href="@Url.Action("Index", new { page = i, pageSize = ViewBag.PageSize })">@i</a>
                    </li>
                }
                @if (Model.HasNextPage)
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber + 1, pageSize = ViewBag.PageSize })">Siguiente</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>