Vinoteca/Vinoteca.Web/Controllers/BodegasController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Vinoteca.Entidades.Entidades;
using Vinoteca.Servicios.Interfaces;
using Vinoteca.Servicios.Servicios;
using Vinoteca.Web.App_Start;
using Vinoteca.Web.ViewModels.Producto;
using Vinoteca.Web.ViewModels.Variedad;
using Vinoteca.Web.Views.Bodegas;

namespace Vinoteca.Web.Controllers
{
    public class BodegasController : Controller
    {
        // GET: Bodegas
        private readonly IServiciosBodegas _servicio;
        private readonly IMapper _mapper;
        public BodegasController(IServiciosBodegas servicios)
        {
            _servicio = servicios;
            _mapper = AutoMapperConfig.Mapper;
        }
        public ActionResult Index(int? page, int? pageSize)
        {
            var lista = _servicio.GetBodegas();
            var listaVm = _mapper.Map<List<BodegaListVm>>(lista);

            page = page ?? 1;
            pageSize = pageSize ?? 10;
            ViewBag.PageSize = pageSize;

            return View(listaVm.ToPagedList(page.Value, pageSize.Value));
        }

        private List<BodegaListVm> GetListaBodegasListVm(List<Bodega> lista)
        {
            var listaVm = new List<BodegaListVm>();
            foreach (var item in lista)
            {
                var bodegaVm = GetBodegaListVm(item);
                listaVm.Add(bodegaVm);
            }
            return listaVm;
        }

        private BodegaListVm GetBodegaListVm(Bodega item)
        {
            return new BodegaListVm()
            {
                BodegaId = item.BodegaId,
                NombreBodega = item.NombreBodega,
                Direccion = item.Direccion,
                RowVersion = item.RowVersion
            };
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BodegaListVm bodegaVm)
        {
            if (ModelState.IsValid)
            {
                var bodega = GetBodegaFromBodegaListVm(bodegaVm);
                if (_servicio.Existe(bodega))
                {
                    ModelState.AddModelError(string.Empty, "Bodega Existente");
                    return View(bodegaVm);
                }
                else
                {
                    _servicio.Guardar(bodega);
                    TempData["Msg"] = "Registro guardado satisfactoriamente";
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(bodegaVm);
            }
        }

        private Bodega GetBodegaFromBodegaListVm(BodegaListVm bodegaVm)
        {
            return new Bodega
            {
                BodegaId = bodegaVm.BodegaId,
                NombreBodega = bodegaVm.NombreBodega,
                Direccion = bodegaVm.Direccion,
                RowVersion = bodegaVm.RowVersion
            };
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var bodega = _servicio.GetBodegaPorId(id.Value);
            if (bodega == null)
            {
                return HttpNotFound("Código de bodega inexistente");
            }
            var bodegaVm = GetBodegaListVm(bodega);
            return View(bodegaVm);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id)
        {
            var bodega = _servicio.GetBodegaPorId(id);
            if (_servicio.EstaRelacionada(bodega))
            {
                var bodegaVm = GetBodegaListVm(bodega);
                ModelState.AddModelError(string.Empty, "Bodega relacionada, baja denegada.");
                return View(bodegaVm);
            }
            _servicio.Borrar(id);
            TempData["Msg"] = "Registro borrado satisfactoriamente";
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var bodega = _servicio.GetBodegaPorId(id.Value);
            if (bodega == null)
            {
                return HttpNotFound("Código de bodega inexistente");
            }
            var bodegaVm = _mapper.Map<BodegaListVm>(bodega);
            return View(bodegaVm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit (BodegaListVm bodegaVm)
        {
            if (!ModelState.IsValid)
            {
                return View(bodegaVm);
            }
            try
            {
                var bodega = _mapper.Map<Bodega>(bodegaVm);
                if (!_servicio.Existe(bodega))
                {
                    _servicio.Guardar(bodega);
                    TempData["Msg"] = "Registro editado satisfactoriamente";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "¡Bodega existente!");
                    return View(bodegaVm);
                }
            }
            catch (System.Exception)
            {
                ModelState.AddModelError(string.Empty, "¡Bodega existente!");
                return View(bodegaVm);
            }
        }
        public ActionResult Details (int? id )
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            var bodega = _servicio.GetBodegaPorId(id.Value);
            if (bodega == null)
            {
                return HttpNotFound("Código de bodega inexistente");
            }
            var bodegaVm = _mapper.Map<BodegaListVm>(bodega);
            return View(bodegaVm);
        }
    }
}

Vinoteca/Vinoteca.Web/Controllers/CarritosController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Vinoteca.Entidades.Entidades;
using Vinoteca.Entidades.Enum;
using Vinoteca.Servicios;
using Vinoteca.Servicios.Interfaces;
using Vinoteca.Web.App_Start;
using Vinoteca.Web.Models;
using Vinoteca.Web.Models.Carrito;
using Vinoteca.Web.ViewModels.Carrito;

namespace Vinoteca.Web.Controllers
{
    public class CarritoController : Controller
    {
        // GET: Carrito
        private readonly IServiciosCarritos _serviciosCarrito;
        private readonly IServiciosProductos _serviciosProductos;
        private readonly IServiciosUsuarios _serviciosUsuarios;
        private readonly IServiciosVentas _serviciosVentas;
        private readonly IMapper _mapper;
        public CarritoController(IServiciosProductos serviciosProductos,
            IServiciosCarritos serviciosCarrito,
            IServiciosUsuarios serviciosUsuarios,
            IServiciosVentas serviciosVentas)
        {
            _serviciosProductos = serviciosProductos;
            _mapper = AutoMapperConfig.Mapper;
            _serviciosCarrito = serviciosCarrito;
            _serviciosUsuarios = serviciosUsuarios;
            _serviciosVentas = serviciosVentas;
        }

        private Carrito _carrito;

        public ActionResult Index(string returnUrl)
        {
            _carrito = GetCarrito();
            if (_carrito.GetCantidad() == 0)
            {
                return View("EmptyCart");
            }
            var listaItem = _carrito.GetItems();
            var listaItemVm = _mapper.Map<List<ItemCarritoVm>>(listaItem);

            CarritoVm carritoVm = new CarritoVm
            {
                Items = listaItemVm,
                returnUrl = returnUrl
            };
            return View(carritoVm);
        }
        public ActionResult MostrarCarrito()
        {
            _carrito = GetCarrito();

            return PartialView("_MostrarCarrito", _carrito);
        }

        private Carrito GetCarrito()
        {
            if (_carrito != null)
            {
                return _carrito;
            }
            _carrito = (Carrito)Session["carrito"];
            if (_carrito == null)
            {
                _carrito = new Carrito();
                Session["carrito"] = _carrito;
            }

            if (_carrito.GetCantidad() == 0)
            {
                if (_serviciosCarrito.GetCantidad(User.Identity.Name) > 0)
                {
                    var listaItemsCarrito = _serviciosCarrito
                        .GetCarrito(User.Identity.Name);
                    foreach (var item in listaItemsCarrito)
                    {
                        _carrito.AddToCart(item);
                    }
                    Session["carrito"] = _carrito;
                }

            }
            return _carrito;
        }

        [HttpPost]
        public ActionResult AddToCart(int productoId, string returnUrl, int cantidad = 1)
        {
            var productoDto = _serviciosProductos.GetProductoPorId(productoId);
            if (productoDto.Stock >= cantidad)
            {
                ItemCarrito itemCarrito = new ItemCarrito
                {
                    ProductoId = productoDto.ProductoId,
                    UserName = User.Identity.Name,
                    NombreProducto = productoDto.Descripcion,
                    PrecioUnitario = productoDto.PrecioVenta,
                    Cantidad = cantidad,

                };
                _carrito = GetCarrito();
                _carrito.AddToCart(itemCarrito);
                Session["carrito"] = _carrito;
                _serviciosCarrito.Guardar(itemCarrito);
                _serviciosProductos.ActualizarUnidadesEnPedido(productoId, cantidad);
                return RedirectToAction("Index", new { returnUrl });

            }
            else
            {
                TempData["Error"] = "Cantidad mayor al stock";
                return RedirectToAction("Index", new { returnUrl });
            }
        }

        public ActionResult RemoveFromCart(int productoId, string returnUrl)
        {
            _carrito = GetCarrito();
            _carrito.RemoveFromCart(productoId);
            Session["carrito"] = _carrito;
            _serviciosCarrito.Borrar(User.Identity.Name, productoId);
            return RedirectToAction("Index", new { returnUrl });

        }

        public ActionResult CancelOrder()
        {
            //TODO: Hacer lo que falta de la cancelación
            _carrito = GetCarrito();
            foreach (var item in _carrito.GetItems())
            {
                _serviciosCarrito.Borrar(User.Identity.Name, item.ProductoId);
            }
            _carrito.Clear();
            Session["carrito"] = _carrito;

            return View();
        }

        public ActionResult ConfirmOrder(string returnUrl)
        {
            //TODO: Hacer la confirmación de la orden
            _carrito = GetCarrito();
            if (_carrito.GetCantidad() == 0)
            {
                return View("EmptyCart");
            }
            var listaItem = _carrito.GetItems();
            var listaItemVm = _mapper.Map<List<ItemCarritoVm>>(listaItem);

            CarritoVm carritoVm = new CarritoVm
            {
                Items = listaItemVm,
                returnUrl = returnUrl
            };
            CheckOutVm model = new CheckOutVm()
            {
                Carrito = carritoVm,
                //Meses = PaymentHelper.GetMeses(),
                //Anios = PaymentHelper.GetAnios(),
            };
            //model.Meses = PaymentHelper.GetMeses();
            //model.Anios = PaymentHelper.GetAnios();
            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmOrderAsync(CheckOutVm model)
        {
            _carrito = GetCarrito();
            var listaItem = _carrito.GetItems();
            var listaItemVm = _mapper.Map<List<ItemCarritoVm>>(listaItem);

            CarritoVm carritoVm = new CarritoVm
            {
                Items = listaItemVm,
            };
            model.Carrito = carritoVm;
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            PaymentResult resultado = CheckOut(model);
            if (resultado.Exitoso)
            {
                TempData["TransaccionId"] = resultado.TransaccionId;
                return RedirectToAction("Complete");
            }
            ModelState.AddModelError(string.Empty, resultado.Mensaje);
            return View(model);

        }
        //private PaymentResult CheckOut(CheckOutVm model)
        //{
        //    Usuario usuario = _serviciosUsuarios.GetUsuarioPorEmail(User.Identity.Name);
        //    var venta = new Venta()
        //    {
        //        UsuarioId = usuario.UsuarioId,
        //        Fecha = DateTime.Now,
        //        Estado = Estado.Impaga,
        //        Importe = _carrito.GetTotal()
        //    };
        //    foreach (var item in model.Carrito.Items)
        //    {
        //        VentaProducto ventaProducto = new VentaProducto()
        //        {

        //            ProductoId = item.ProductoId,
        //            Cantidad = item.Cantidad,
        //            Precio = item.PrecioTotal,

        //        };
        //        venta.Detalles.Add(ventaProducto);
        //    }
        //    //TODO:Autorizar el pago
        //    var checkout = new CheckOut()
        //    {
        //        Venta = venta,
        //        CardNumber = model.CardNumber,
        //        CVV = model.CVV,
        //        Month = model.Month,
        //        Year = model.Year,
        //    };
        //    var gateway = new PaymentGateway();
        //    var resultado = gateway.ProcesarPago(checkout);
        //    if (resultado.Exitoso)
        //    {
        //        _carrito = GetCarrito();
        //        _carrito.Clear();
        //        Session["carrito"] = _carrito;

        //        venta.TransaccionId = resultado.TransaccionId;
        //        _serviciosVentas.Guardar(venta, User.Identity.Name);

        //    }
        //    //TODO:Obtener TransaccionId
        //    return resultado;
        //}

        private PaymentResult CheckOut(CheckOutVm model)
        {
            Usuario usuario = _serviciosUsuarios.GetUsuarioPorEmail(User.Identity.Name);
            var venta = new Venta()
            {
                UsuarioId = usuario.UsuarioId,
                Fecha = DateTime.Now,
                Estado = Estado.Impaga,
                Importe = _carrito.GetTotal()
            };
            foreach (var item in model.Carrito.Items)
            {
                VentaProducto ventaProducto = new VentaProducto()
                {

                    ProductoId = item.ProductoId,
                    Cantidad = item.Cantidad,
                    Precio = item.PrecioTotal,

                };
                venta.Detalles.Add(ventaProducto);
            }
            //TODO:Autorizar el pago
            var checkout = new CheckOut()
            {
                Venta = venta,
                CardNumber = model.CardNumber,
                CVV = model.CVV,
                Month = model.Month,
                Year = model.Year,
            };
            var gateway = new PaymentGateway();
            var resultado = gateway.ProcesarPago(checkout);
            if (resultado.Exitoso)
            {
                _carrito = GetCarrito();
                _carrito.Clear();
                Session["carrito"] = _carrito;

                venta.TransaccionId = resultado.TransaccionId;
                _serviciosVentas.Guardar(venta, User.Identity.Name);

            }
            //TODO:Obtener TransaccionId
            return resultado;

Vinoteca/Vinoteca.Web/Controllers/VentasController.cs
using Antlr.Runtime.Misc;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vinoteca.Servicios.Interfaces;
using Vinoteca.Web.App_Start;
using Vinoteca.Web.ViewModels.Venta;

namespace Vinoteca.Web.Controllers
{
    public class VentasController : Controller
    {
        // GET: Ventas
        private readonly IServiciosVentas _servicios;
        private readonly IMapper _mapper;
        public VentasController(IServiciosVentas servicios)
        {
            _servicios = servicios;
            _mapper = AutoMapperConfig.Mapper;
        }
        public ActionResult Index()
        {
            var lista = _servicios.GetVentas();
            var listaVm = _mapper.Map<List<VentaListVm>>(lista);
            return View(listaVm);
        }
    }
}

Vinoteca/Vinoteca.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAeTQmuim0yo13wC_RZscH4zGN0ZSBl_JE&callback=initMap" defer></script>
</head>

<body>
    
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            <div style="margin-right:1em">
                <img class="d-block mx-auto mb-1 mt-1" src="@Url.Content(Vinoteca.Utilidades.WC.Logo2)" alt="" width="80" height="80" style="border-radius:30px">
            </div>
            @Html.ActionLink("Vinoteca Ramón", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Variedades", "Index", "Variedades", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Productos", "Index", "Productos", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Archivos
                        </a>
                        <ul class="dropdown-menu">
                            @if (User.IsInRole("Admin"))
                            {
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Bodegas", new { area = string.Empty })">Bodegas</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index", "Ventas", new { area = string.Empty })">Ventas</a></li>
                                <li><hr class="dropdown-divider"></li>
                            }
                        </ul>
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Seguridad
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="@Url.Action("Index","RolesAdmin",new {area="Identity"})">Roles</a></li>
                                <li><a class="dropdown-item" href="@Url.Action("Index","UsersAdmin",new {area="Identity"})">Usuarios</a></li>

                            </ul>
                        </li>
                    }
                </ul>
            </div>
            @Html.Partial("_LoginPartial")
            @if (User.IsInRole("Usuario"))
            {
                 @Html.Action("MostrarCarrito", "Carrito")
            }
        </div>      
    </nav>

    <div class="container body-content">
        @Html.Partial("_Notification")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

Vinoteca/Vinoteca.Web/Views/Shared/_MostrarCarrito.cshtml
@model Vinoteca.Web.Models.Carrito.Carrito
@{
    string returnUrl = "Productos";
}
<form class="d-flex" action="@Url.Action("Index", "Carrito", new {returnUrl})">
    <button class="btn btn-outline-light" type="submit">
        <i class="fa fa-shopping-cart me-1"></i>
        Carrito
        <span class="badge bg-light text-dark ms-1 rounded-pill">@Model.GetCantidad()</span>
    </button>
</form>

Vinoteca/Vinoteca.Web/Views/Shared/_MostrarProducto.cshtml
@model Vinoteca.Web.ViewModels.Producto.ProductoEditVm
<div class="row">
    <div class="col-6">
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BodegaId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BodegaId, Model.Bodegas, "Seleccione Bodega", new { @class = "form-select" })
                @Html.ValidationMessageFor(model => model.BodegaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VariedadId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.VariedadId, Model.Variedades, "Seleccione Variedad", new { @class = "form-select" })
                @Html.ValidationMessageFor(model => model.VariedadId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoProductoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoProductoId, Model.TiposProductos, "Seleccione Tipo Producto", new { @class = "form-select" })
                @Html.ValidationMessageFor(model => model.TipoProductoId, "", new { @class = "text-danger" })
            </div>
        </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Suspendido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Suspendido)
                @Html.ValidationMessageFor(model => model.Suspendido, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.imagenFile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span class="btn btn-default btn-file">
                @Html.TextBoxFor(model => model.imagenFile, new { type = "file" })
            </span>
        </div>
    </div>
        </div>
    <div class="col-6">
        <div class="form-group">
            @Html.LabelFor(model => model.PrecioVenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecioVenta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecioVenta, "", new { @class = "text-danger" })
            </div> 
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FichaTecnica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.FichaTecnica, htmlAttributes: new { style = "width: 100%; max-width: 100%; height: 300px" })
                @Html.ValidationMessageFor(model => model.FichaTecnica, "", new { @class = "text-danger"  })
            </div>
        </div>

    </div>
</div>

Vinoteca/Vinoteca.Web/Views/Shared/_Notification.cshtml
@if (TempData["Msg"] != null)
{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Msg"]')
    </script>
}
@if (TempData["Error"] != null)
{
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
    </script>
}